### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Marctraider** [JamesGKent/cockpit-sensors-plugin#2] opened 2019-11-01 01:23 UTC
Hi! 

It just keeps adding a new column going down continuously.

root@redundant:~# sensors
acpitz-virtual-0
Adapter: Virtual device
temp1:        +41.0°C  (crit = +95.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +41.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:         +42.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:         +41.0°C  (high = +105.0°C, crit = +105.0°C)

![bug](https://user-images.githubusercontent.com/29001732/67996156-6e519600-fc4e-11e9-9225-a7760acc475f.png)

**Comment by brendantay** [comment] 2020-01-27 07:43
@Marctraider check out my pull req #3 
This change resolved the issue for me too which was caused by the first output being Package id 0 (in your case Physical id 0)

I'm no coder, so its probably not the best way to handle it, but it works for me - and should for you too based on your presented screenshot.

**Comment by JamesGKent** [comment] 2020-05-01 14:02
I believe this should be fixed with the pull request from @brendantay

**Closed as completed by JamesGKent** 2020-05-01 14:02 UTC
